name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Install Linter
        run: mvn -q -B -DskipTests=true validate

      - name: Run Checkstyle
        run: mvn -q -B checkstyle:checkstyle

      - name: Upload Checkstyle Result
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle.xml
          path: target/checkstyle-result.xml
          if-no-files-found: warn

      - name: Run Maven Test
        run: mvn -q -B test

      - name: Jacoco Report
        run: mvn -q -B verify

      - name: Upload Jacoco Coverage
        uses: actions/upload-artifact@v4
        with:
          name: jacoco.xml
          path: target/site/jacoco/jacoco.xml
          if-no-files-found: warn
